name: 🐛 Bug Report
description: Report a possible bug or regression in the PowerShell profile
title: "🐛 <TITLE>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thank you for submitting the bug! We'll try to triage it ASAP!
  - type: markdown
    attributes:
      value: |
        Bug reports that don't follow this template will be closed.
        Please provide a clear and concise description of what the bug is.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A summary of the bug and its impact on the PowerShell profile.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug, including any relevant commands or scripts.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots or error messages.
    validations:
      required: false
