#Requires -Version 5.1
<#
.SYNOPSIS
    Reads the command reference for a module out of its source.

.DESCRIPTION
    Dot-source this to get Get-ModuleCommand, shared by Tools/Update-Readme.ps1 (which writes the
    generated section) and Tools/Test-Readme.ps1 (which verifies it is current). One
    implementation means generated and checked cannot disagree.

    Synopsis text comes from each function's own comment-based help via GetHelpContent, so the
    comment-based help is the single source of truth. Aliases and export status come from the same
    derivation the manifests use.

.LINK
    https://github.com/MKAbuMattar/powershell-profile
#>

Set-StrictMode -Version Latest

$script:BeginMarker = '<!-- BEGIN GENERATED COMMANDS -->'
$script:EndMarker = '<!-- END GENERATED COMMANDS -->'

function Format-CommandTable {
    <#
    .SYNOPSIS
        Renders command rows as the generated markdown block, markers included.

    .PARAMETER Command
        Rows from Get-ModuleCommand.

    .PARAMETER ModuleName
        Base name of the module, used in the generated-by comment.

    .OUTPUTS
        [string] The block, from the begin marker to the end marker.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [PSCustomObject[]]$Command,
        [Parameter(Mandatory)][string]$ModuleName
    )

    $lines = [System.Collections.Generic.List[string]]::new()

    $lines.Add($script:BeginMarker)
    $lines.Add('')
    $lines.Add("<!-- Generated by Tools/Update-Readme.ps1 from the comment-based help in $ModuleName.psm1. -->")
    $lines.Add('<!-- Edit the help in the source, then re-run the tool. Changes here are overwritten. -->')
    $lines.Add('')

    if (-not $Command -or @($Command).Count -eq 0) {
        $lines.Add('This module exports no commands.')
        $lines.Add('')
        $lines.Add($script:EndMarker)
        return ($lines -join "`n")
    }

    $lines.Add('| Command | Alias | Description |')
    $lines.Add('| --- | --- | --- |')

    foreach ($row in $Command) {
        $aliases = if (@($row.Aliases).Count) {
            ((@($row.Aliases) | ForEach-Object { '`' + $_ + '`' }) -join ', ')
        }
        else {
            ''
        }

        # Escape pipes so a synopsis containing one cannot break the table.
        $synopsis = $row.Synopsis -replace '\|', '\|'

        $lines.Add(('| `{0}` | {1} | {2} |' -f $row.Name, $aliases, $synopsis))
    }

    $lines.Add('')
    $lines.Add(('{0} command(s).' -f @($Command).Count))
    $lines.Add('')
    $lines.Add($script:EndMarker)

    return ($lines -join "`n")
}

function Merge-ReadmeContent {
    <#
    .SYNOPSIS
        Returns README content with the generated block replaced.

    .DESCRIPTION
        Replaces only the text between the markers, so hand-written prose around it survives.
        A README with no markers gets a Commands section appended once.

        Both Update-Readme.ps1 and Test-Readme.ps1 call this, which is what makes "generated" and
        "checked" mean the same thing. An earlier version of Test-Readme parsed the generator's
        Write-Host output instead and silently always passed, because Write-Host does not go to a
        stream that redirection can capture.

    .PARAMETER Content
        Current README content.

    .PARAMETER Table
        The block from Format-CommandTable.

    .OUTPUTS
        [string] The updated content, newline-normalised.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)][AllowEmptyString()][string]$Content,
        [Parameter(Mandatory)][string]$Table
    )

    $normalised = $Content -replace "`r`n", "`n"

    $beginIndex = $normalised.IndexOf($script:BeginMarker)
    $endIndex = $normalised.IndexOf($script:EndMarker)

    if ($beginIndex -ge 0 -and $endIndex -gt $beginIndex) {
        return $normalised.Substring(0, $beginIndex) +
        $Table +
        $normalised.Substring($endIndex + $script:EndMarker.Length)
    }

    return $normalised.TrimEnd() + "`n`n## Commands`n`n" + $Table + "`n"
}

function Get-ModuleCommand {
    <#
    .SYNOPSIS
        Returns the exported commands of a module with their aliases and synopsis.

    .PARAMETER ModulePath
        Path to the .psm1 to read.

    .PARAMETER Policy
        The hashtable loaded from Tools/ExportPolicy.psd1.

    .OUTPUTS
        [PSCustomObject[]] One row per exported function: Name, Aliases, Synopsis.

    .EXAMPLE
        Get-ModuleCommand -ModulePath ./Module/Network/Network.psm1 -Policy $policy
    #>
    [CmdletBinding()]
    [OutputType([PSCustomObject[]])]
    param(
        [Parameter(Mandatory, Position = 0)]
        [string]$ModulePath,

        [Parameter(Mandatory, Position = 1)]
        [hashtable]$Policy
    )

    $tokens = $null
    $errors = $null
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($ModulePath, [ref]$tokens, [ref]$errors)
    if ($errors) { return @() }

    $definitions = @($ast.FindAll(
            { param($node) $node -is [System.Management.Automation.Language.FunctionDefinitionAst] },
            $true))

    # Follow dot-sourced files the same way the manifest generator does, so a module split across
    # several .ps1 files documents all of itself.
    $moduleDirectory = Split-Path -Parent $ModulePath

    foreach ($command in $ast.FindAll(
            { param($node)
                $node -is [System.Management.Automation.Language.CommandAst] -and
                $node.InvocationOperator -eq [System.Management.Automation.Language.TokenKind]::Dot },
            $true)) {

        $literal = $command.FindAll(
            { param($node)
                $node -is [System.Management.Automation.Language.StringConstantExpressionAst] -and
                $node.Value -like '*.ps1' },
            $true) | Select-Object -First 1

        if (-not $literal) { continue }

        $included = Join-Path $moduleDirectory $literal.Value
        if (-not (Test-Path -LiteralPath $included)) { continue }

        $includedErrors = $null
        $includedTokens = $null
        $includedAst = [System.Management.Automation.Language.Parser]::ParseFile($included, [ref]$includedTokens, [ref]$includedErrors)
        if ($includedErrors) { continue }

        $definitions += @($includedAst.FindAll(
                { param($node) $node -is [System.Management.Automation.Language.FunctionDefinitionAst] },
                $true))
    }

    $rows = foreach ($definition in $definitions) {
        if ($definition.Name -in $Policy.PrivateFunctions) { continue }

        $aliases = @()
        $paramBlock = $definition.Body.ParamBlock

        if ($paramBlock) {
            foreach ($attribute in $paramBlock.Attributes) {
                if ($attribute.TypeName.Name -ne 'Alias') { continue }
                foreach ($argument in $attribute.PositionalArguments) {
                    $name = $argument.Value
                    if (-not $name) { continue }
                    if ($name -in $Policy.ReservedAliases) { continue }
                    if ($name -eq $definition.Name) { continue }
                    $aliases += $name
                }
            }
        }

        $help = $definition.GetHelpContent()
        $synopsis = if ($help -and $help.Synopsis) {
            # Collapse the synopsis to one line; a table cell cannot hold a paragraph.
            ($help.Synopsis -replace '\s+', ' ').Trim()
        }
        else {
            ''
        }

        [PSCustomObject]@{
            Name     = $definition.Name
            Aliases  = @($aliases)
            Synopsis = $synopsis
        }
    }

    return @($rows | Sort-Object Name)
}
